# Generated by Django 3.1.7 on 2021-03-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('demo_link', models.CharField(max_length=300)),
                ('repo_link', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Code project',
                'verbose_name_plural': 'Code projects',
            },
        ),
    ]
